### ISSUE TITLE
Some speakers are misclassified as `candidate==0` 

### ISSUE THREAD

**Issue by zilinskyjan** [jamesmartherus/debates#1]
James, thank you for putting this great resource together!

FYI, there appear to be 3 cases in 2020 primary debates when a speaker is classified as not being a candidate

* John Delaney
* "Bill deBlasio" (but "Bill DeBlasio" rows are classified correctly)
* Kamala Harris (but only in one dabate: 2020-10-08)

(I noticed this while running `debate_transcripts %>% filter(election_year==2020) %>% group_by(candidate) %>% count(speaker) %>% View()` )

**Comment by jamesmartherus** [comment]
Hi Jan,

Thanks for the heads up! I’ll take care of this tomorrow.

Best,
James

**Comment by jamesmartherus** [comment]
This is fixed by ceda9c964fe8e375642ed6a997087ebea52f7a1a.

Thanks for the heads up!

**Comment by zilinskyjan** [comment]
Terrific, thank you!
