### ISSUE TITLE
Gerald Ford is misclassified

### ISSUE THREAD

**Issue by JavierBJ** [jamesmartherus/debates#2]
Hi,

First, thank you very much for making this awesome resource so easily usable! It was extremely valuable for us.

I found that all rows by president Gerald Ford are classified as `candidate=0` and, if you can't find him, that's because his speaker value is incorrectly labeled as `Gerlad Ford` :sweat_smile: .

Kind regards

**Comment by jamesmartherus** [comment]
Thanks for bringing that to my attention! This should be fixed by 59a46a0.
