### ISSUE TITLE
John Edwards observations coded as presidential debates

### ISSUE THREAD

**Issue by agadjanian** [jamesmartherus/debates#3]
Hi @jamesmartherus, thanks so much for your work in creating this amazing resource! 

I think I found a small error: there are two observations for John Edwards coded as "Pres" in the `type` variable. For example, running the following:
```
library(debates)
data(debate_transcripts)
table(debate_transcripts$speaker[debate_transcripts$type=="Pres" & debate_transcripts$candidate==1], exclude = F)
```
Gets you this:
![image](https://user-images.githubusercontent.com/19782185/115508680-73cfe100-a232-11eb-9938-831da9c6ef91.png)

I was focusing only on the general election presidential debates data, so I'm not sure if there are also issues for John Edwards in other `type` values (e.g. in primary or VP debates data).

Unrelated question: just wanted to check, but the missing debates between 1960 and 1976 was intentional/something you were aware of, right? Again, just want to make sure it wasn't supposed to be in the data or anything.

**Comment by jamesmartherus** [comment]
Ah, nice catch on John Edwards! I'll look into that. 

Fun fact, there were no general presidential debates between 1960 and 1972, as Johnson refused in 64 and Nixon refused in 68 and 72. There were primary debates, but I haven't gotten around to digging up any primary debate transcripts prior to 2012.

**Comment by agadjanian** [comment]
Oh interesting! I was wondering if it was something like that -- thanks for clarifying, that's good to know.

**Comment by jamesmartherus** [comment]
This is now fixed. Turns out there was a panelist on one of the 1960 debates named John Edwards.
